version: "4.1.3"

services:
  # service of WEB
  tnut-wordpress:
    image: wordpress:latest
    ports:
      - "8062:80"
    user: 1001:1001
    environment:
      WORDPRESS_DB_HOST: tnut-db
      WORDPRESS_DB_USER: it_aum
      WORDPRESS_DB_PASSWORD: It_aum@2024
      WORDPRESS_DB_NAME: db_tnut
    volumes:
      - ./tnut-wordpress-vol:/var/www/html
    networks:
      - frontend
      - backend

  tnut-db:
    image: mysql:5.7
    restart: always
    user: 1001:1001
    environment:
      MYSQL_ROOT_PASSWORD: It_aum@root@2024
      MYSQL_DATABASE: db_tnut
      MYSQL_USER: it_aum
      MYSQL_PASSWORD: It_aum@2024
    volumes:
      - ./tnut-db-vol:/var/lib/mysql
    networks:
      - backend


  tnut-nextjs:
    build:
      context: ./tnut-uat-redis
    ports:
      - "3003:3000"
    networks:
      - frontend


  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  tnut-wordpress-vol:
  tnut-db-vol:
  redis_data:

networks:
  frontend:
  backend:
